feat: 사용자 등록 기능 추가
younlll/real-world-app pull request #3
Opened 2022-03-07 03:59 UTC by younlll

2022-03-07 04:37 UTC, Rebwon requested changes
패키지 명을 분리하셨다면 각 패키지에 용도에 맞게 적절한 코드 배치가 필요해보입니다 :)

2022-03-07 04:37 UTC, Rebwon commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
Jdbc 의존성을 제거하고 JPA를 넣으신 이유가 있을까요?

2022-03-07 04:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
생성자 주입을 활용하시는 것은 좋으나, @Autowired는 안붙이셔도 됩니다.

혹시 스프링에서 왜 생성자 주입을 권장하는지 이유를 아시나요?

2022-03-07 04:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/controller/UserController.java
> +    private UserService userService;
여기도 역시 Autowired는 안붙이셔도 됩니다. 그리고 RequiredArgsConstructor 애너테이션에 대해 알아보시면 좋을 것 같습니다 :)

2022-03-07 04:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/domain/RegistrationUserForm.java
> +    private String username;
회원가입 시 클라이언트로부터 들어오는 값의 유효성을 검사할 필요가 있어 보입니다.

2022-03-07 04:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/domain/RegistrationUserForm.java
> +public class RegistrationUserForm {
Data만 붙이셔도 됩니다 :)

2022-03-07 04:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/domain/User.java
> +public class User {
테이블 생성 용도로 만들어놓으신건가요?

2022-03-07 04:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    RegistrationUserForm registrationUser(RegistrationUserForm userForm);
RegistrationUserForm이 도메인에 있어야 할까요?

2022-03-07 04:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    List<User> inqUserEmail(String email);
이메일 조회 메서드라면 boolean을 사용하고 조금 더 가독성 있는 메서드 명을 고려해보시는게 좋을 것 같아요 :)

2022-03-07 12:27 UTC, younlll commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
@Entity가 객체랑 테이블을 맵핑해준다라고 알아서 선언을 햇는데
이건 jpa를 의존성에 넣은거였거든요

근데 지금 찾아보니까 
jpa로 작성할때 @Entity를 선언해서 테이블과 맵핑을 해주는거 같네요

2022-03-07 12:32 UTC, younlll commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
생성자 주입을 하게되면 생성자 호출할 때 한번만 호출되서 주입되고 이후에 변경되지 않는 것을 보장하기 때문에 권장한다고 알고 있습니다

2022-03-07 12:34 UTC, younlll commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
@Autowired를 안붙여도 된다고 하신건 생성자가 1개만 존재해서 생략해도 자동 주입 되기 때문일까요?

2022-03-07 12:44 UTC, younlll commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    RegistrationUserForm registrationUser(RegistrationUserForm userForm);
사용자 등록 정보를 담는 곳이라 생각해서 도메인에 넣어둔거였는데...
도메인으로 분류되는게 아닌걸까요?

2022-03-07 12:46 UTC, younlll commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    List<User> inqUserEmail(String email);
메서드 명은 가독성 있는거로 고민해보겠습니다

이메일을 통해 조회가 이후에 있을 수도 있을거라 생각되서 User정보를 조회하게끔 했는데
지금 사용자의 이메일을 통한 조회는 중복된 사용자 등록을 확인하기 위함이기 때문에 boolean으로 두는게 좋다는거로 이해하면 될까요?

만약 이후에 이메일을 통해 특정 정보를 조회하는 경우가 필요하다면 그때는 다른 메서드로 선언하는게 구현에 조금 더 맞는걸까요?

2022-03-07 12:48 UTC, younlll commented on src/main/java/com/youn/realworldapp/controller/UserController.java
> +    private UserService userService;
RequiredArgsConstructor 어노테이션은 final이나 @Notnull이 붙은 필드의 생성자를 만들어주는 역할이라고 하네요
그럼 이 부분은 final을 붙여서 userService 필드를 생성해주고 RequiredArgsConstructor 어노테이션을 붙여주면 될거같네요

2022-03-07 12:49 UTC, younlll commented on src/main/java/com/youn/realworldapp/domain/User.java
> +public class User {
현재 User객체가 필요한게 아니기 때문에 구현되지 않아도 되는건가요?

2022-03-07 13:22 UTC, younlll commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    RegistrationUserForm registrationUser(RegistrationUserForm userForm);
>DTO를 사용하는 이유로, User 라는 Domain 에 name 이 모든 request 및 response 에 필요하지 않음에도 
불필요하게 사용될 수 있으며, 만약 각 API 의 request 와 response 에 맞추기 위해
domain 이 수정되서는 안되기 떄문입니다.
>
>따라서 각 DTO 에 필요한 데이터만 정의 되어야하며, 필수 값에 대한 조건 체크하는 것이나
DTO 에서 Domain 으로 변환하거나
Domain 에서 DTO 로 변환하는 로직은 Domain 이 아닌 DTO 에 담겨야 합니다.
>
>따라서, 위의 @NotNull 과 같은 Data 의 Validation 도 DTO 의 역할 이기 때문에 DTO 에 넣어주게 되면 역할과 책임이 좀 더 명백해지게 됩니다

라고 되어있는걸 찾게되었습니다

이 내용을 보니까 RegistrationUserForm 이것은 도메인이 아니라 request와  response에 맞추기 위해서 만들어진 클래스이니까
별도 패키지(dto)를 생성해서 분리를 해야한다는 생각이 드네요

2022-03-07 22:12 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
조금 더 자세히 알아보시는게 좋을 거 같습니다. 몇가지 중요한 내용이 누락되어있네요 :)

2022-03-07 22:13 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/controller/UserController.java
> +    private UserService userService;
💯

2022-03-07 22:14 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    RegistrationUserForm registrationUser(RegistrationUserForm userForm);
넵 맞습니다. 💯

2022-03-07 22:15 UTC, Rebwon commented on build.gradle
> +	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
JPA로 개발하실게 아니라면, 제거하시는게 맞습니다.

2022-03-07 22:16 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/domain/User.java
> +public class User {
User 객체는 필요한데, JPA가 아니어도 구현이 되기 때문에 JPA 없이 해보시는 것도 좋을 것 같네요

2022-03-07 22:19 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    List<User> inqUserEmail(String email);
네, 맞습니다. 유저가 단순히 존재하는지 여부만 확인하는 메서드와 유저의 정보를 가져오는 메서드를 분리하라는 의미였습니다. 이건 스프링 데이터 JPA의 repository 클래스를 찾아보시거나, existsBy라는 네이밍 쿼리에 대해 알아보셔도 좋겠네요.

2022-03-07 22:21 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/repository/JdbcTemplateUserRepository.java
> +    }
이 부분에서, Repository 클래스가 Dto를 직접 받지 않도록 해보시고, 반환 값도 Dto를 리턴하지 않도록 변경하시는게 좋습니다. CQS라는 원칙을 찾아보시면 좋겠네요 :)

2022-03-08 13:04 UTC, younlll commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
1. 생성자 호출할 때 한번만 호출되서 주입되고 이후에 변경되지 않는 것을 보장합니다
2. final 키워드를 붙임으로써 누락을 방지해줍니다
3. 필드 주입이나 수정자(setter)주입은 객체 생성 시점에 순환 잠조가 일어나는지 알 수가 없어서 스프링 어플리케이션 구동 시에 정상으로 작동하고 실제 코드가 호출될 때 오류를 발생 시킵니다
이에 반해, 생성자 주입은 빈 생성 시에 순환 참조 되는 것을 발견할 수 있어 스프링 어플리케이션 구동 시 순환 참조를 발견할 수 있습니다.
4. 필드 주입은 단위 테스트 시에 의존 관계를 가지는 객체를 생성해서 주입할 수가 없어 NullPointException이 발생하지만 생성자 주입은 객체 생성 시, 원하는 구현체를 넘겨주면 되므로 테스트 코드 작성하기가 좋습니다

2022-03-08 13:06 UTC, younlll commented on src/main/java/com/youn/realworldapp/domain/RegistrationUserForm.java
> +    private String username;
@Email을 통해서 이메일 형식 검사를 추가하고
3개의 컬럼들에 @NotBlank를 통해서 NULL, ""(String 초기화), " "(공백) 검사가 되도록 추가했습니다

2022-03-08 13:07 UTC, younlll commented on src/main/java/com/youn/realworldapp/domain/User.java
> +public class User {
User객체를 도메인으로 생성은 했는데
도메인을 통한 값의 변경을 방지하기 위해서 @Data대신에 @Getter만 생성했습니다
또 @AllArgsConstructor를 통해서 모든 컬럼을 파라미터로 받는 생성자를 통해서만 값이 들어올 수 있도록 변경했습니다

2022-03-08 13:11 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
final을 붙이면 누락을 방지하는 건가요?

2022-03-09 10:09 UTC, younlll commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
final을 붙이면서 반드시 초기화를 해줘야하고 생성자를 통한 주입의 누락을 알 수 있다라고 찾았었는데..
잘 못 알게된걸까요

2022-03-09 10:10 UTC, younlll commented on src/main/java/com/youn/realworldapp/repository/UserRepository.java
> +    List<User> inqUserEmail(String email);
exists로 쿼리 조회를 해서 boolean형으로 반환 될 수 있게끔 변경 했습니다.
existsBy나 countBy와 같은 것들을 알게 되었네요

2022-03-09 10:19 UTC, younlll commented on src/main/java/com/youn/realworldapp/repository/JdbcTemplateUserRepository.java
> +    }
1.dto를 직접 받지 않고 2.CQS 원칙 을 찾아보면서
view <-> controller = dto
service <-> db = entity
라는 것을 찾게 되었는데요

dto에 메서드를 만들어서 toDto, toEntity를 수행해줘서 변환하여 사용하도록 만들었습니다
그래서 repository에 entity를 받고 반환하게끔 변경을 하게 되었는데

이게 요구하신걸 맞게 이해하고 찾아서 수정된건지 확신이 없네요

또 궁금한 점은
CQS가
질의(쿼리)는 데이터의 변경이 없으면서 반환을 해야하고
명령은 데이터의 변경은 있지만 반환하면 안된다 라고 설명이 되어있던데
이게 excute메서드를 통해 insert를 수행한 뒤에 반환 값을 받지 말아야한다는 의미인지
아니면 insert를 수행시키는 메서드(현재 구현되어 있는 코드에서는 registrationUser())의 리턴값이 void여야 한다는 의미인지 햇갈리네요

+ 말씀하신 클린 코더스 강의를 보면서 더 이해해보도록 해야겠습니다

2022-03-09 10:21 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
final 키워드 자체에 대해 공부해보시는게 좋을 것 같네요. 추가로 Immutable이라는 것도 연관지어서 알아보시면 좋을 것 같습니다 :)

2022-03-09 10:22 UTC, Rebwon approved these changes

2022-03-09 14:56 UTC, younlll commented on src/main/java/com/youn/realworldapp/SpringConfig.java
> +    }
final은 다른 참조나 다른 객체를 가리키도록 객체의 참조를 변경할 수 없지만 여전히 상태를 변경할 수 있음을 의미한다고 하네요(예: setter 메서드 사용)
immutable은 객체의 실제 값을 변경할 수 없지만 참조를 다른 값으로 변경할 수 있음을 의미한다고 합니다

![image](https://user-images.githubusercontent.com/62369538/157464573-b070f1c2-db98-4126-8702-c26b8d03659b.png)

2022-03-09 22:25 UTC, Rebwon commented
이번 작업은 여기서 병합하시고, 이제 회원 가입할 때, 비밀번호를 암호화하는 기능을 추가해보시면 좋을 것 같습니다 :)

2022-03-10 00:35 UTC, merged