feat: 로그인 기능 추가
younlll/real-world-app pull request #6
Opened 2022-03-13 00:36 UTC by younlll

사이트 보면 인증하는게 있어서 해보려는데 너무 어렵네요ㅠㅠ

2022-03-13 03:37 UTC, Rebwon requested changes
JWT 토큰 인증 구현이 쉽지 않으시다면, 세션 기반으로 먼저 로그인을 구현해보시는 것이 좋을 것 같습니다 :)

2022-03-13 03:37 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/repository/JdbcTemplateUserRepository.java
> +        );
List<User>로 가져오시는 것이 과연 최선일까요?

2022-03-13 13:08 UTC, younlll commented on src/main/java/com/youn/realworldapp/repository/JdbcTemplateUserRepository.java
> +        );
rowmapper를 통해서 가져온다는게 list라는 느낌을 줘서 쓰게된거 같네요;;;
이것도 docs보면서 queryForObject로 Long.class, String.class말고도 객체 클래스도 지정할 수 있는 것을 보고 변경을 해보았습니다

List로 가져오는 것이 최선이 아닌 이유가
email을 통해서 중복가입을 방지하고 있기때문에 값이 1개인게 보장이 되어서 객체로 받는게 좋다라고 이해해도 되는 걸까요?

2022-03-13 13:10 UTC, younlll commented
JWT 토큰 인증 구현에 대해 조금 더 공부해보고 계속 이해가 안된다면 세션 기반으로 구현해보겠습니다

2022-03-13 23:09 UTC, Rebwon commented on src/main/java/com/youn/realworldapp/repository/JdbcTemplateUserRepository.java
> +        );
네 맞습니다. 한 건을 검사하는데 List 타입으로 받는다는 건 해당 이메일이 여러 개 있을 수 있다고 오해할 여지가 있습니다.

2022-03-14 11:36 UTC, Rebwon approved these changes

2022-03-14 11:37 UTC, merged